# Generated by Django 4.2.8 on 2024-01-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название Категории', max_length=128, unique=True, verbose_name='Категория')),
                ('slug', models.CharField(help_text='URL Категории', max_length=128, unique=True, verbose_name='URL Категории')),
                ('description', models.TextField(help_text='Опишите Категорию', max_length=256, verbose_name='Описание Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название Товара', max_length=128, verbose_name='Имя Товара')),
                ('slug', models.CharField(max_length=128, verbose_name='URL Продукта')),
                ('description', models.TextField(help_text='Опишите Товар', max_length=256, verbose_name='Описание Товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите Цену Товара', max_digits=6, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Введите Количество Товара', verbose_name='Количество Товара')),
                ('image', models.ImageField(help_text='Загрузите Фото', upload_to='product_image', verbose_name='Фото Товара')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время Создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='Видимость Товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.category', verbose_name='Категория Товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('time_update',),
            },
        ),
    ]
