# Generated by Django 4.2.8 on 2024-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(max_length=128, unique=True, verbose_name='URL Продукта'),
        ),
    ]
